# This file is used for local authoring and testing the Russian help system without actually building the help.
# To actually build the help with all the dependencies run `buildhelp.ps1`.
# To test and author the Russian help run:
# py -m mkdocs serve (`mkdocs serve` might also work depending on the environment PATH variable)
# To test and author the English help run: py -m mkdocs serve -f mkdocs_en_local.yml

INHERIT: mkdocs_guide_complete_ru.yml
